services:
  postgres:
    image: postgres:16
    container_name: student_management_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: student_admin
      POSTGRES_PASSWORD: student_password
      POSTGRES_DB: student_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: