'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useAssignment, useAssignmentSubmissions } from '@/lib/hooks/use-assignments';
import { useAuth } from '@/lib/hooks/use-auth';
import { buttonVariants } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { LoadingState } from '@/components/states/LoadingState';
import { ErrorState } from '@/components/states/ErrorState';
export default function AssignmentDetailPage() { const { id } = useParams<{ id: string }>(); const assignment = useAssignment(Number(id)); const submissions = useAssignmentSubmissions(Number(id)); const { user } = useAuth(); if (assignment.isLoading) return <LoadingState />; if (assignment.isError || !assignment.data) return <ErrorState title="Assignment unavailable" onRetry={() => assignment.refetch()} />; const a = assignment.data; return <div className="mx-auto max-w-3xl space-y-6"><div className="flex items-center justify-between"><div><p className="text-sm uppercase tracking-[0.2em] text-muted-foreground">Assignment</p><h1 className="text-3xl font-semibold">{a.title}</h1></div>{user?.role === 'admin' && <Link className={buttonVariants()} href={`/assignments/${a.id}/edit`}>Edit</Link>}</div><Card><CardHeader><CardTitle>Assignment details</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>{a.description || 'No description provided.'}</p><p>Subject: #{a.subject_id}</p><p>Academic class: #{a.academic_class_id}</p><p>Due date: {a.due_date}</p></CardContent></Card><Card><CardHeader><CardTitle>Submissions</CardTitle></CardHeader><CardContent>{submissions.isLoading ? <LoadingState rows={2} /> : submissions.isError ? <ErrorState title="Submissions unavailable" onRetry={() => submissions.refetch()} /> : !submissions.data?.items.length ? <p className="text-sm text-muted-foreground">No submissions recorded.</p> : <div className="space-y-2">{submissions.data.items.map((s) => <div key={s.id} className="flex justify-between border-b py-2 text-sm"><span>Student #{s.student_id}</span><span className="capitalize">{s.status} {s.submitted_at ? `· ${s.submitted_at}` : ''}</span></div>)}</div>}</CardContent></Card></div>; }
