'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useAssignments, useDeleteAssignment } from '@/lib/hooks/use-assignments';
import { useAuth } from '@/lib/hooks/use-auth';
import { buttonVariants } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { LoadingState } from '@/components/states/LoadingState';
import { ErrorState } from '@/components/states/ErrorState';
import { EmptyState } from '@/components/states/EmptyState';
export default function AssignmentsPage() { const [page, setPage] = useState(1); const { user } = useAuth(); const admin = user?.role === 'admin'; const q = useAssignments({ page, page_size: 20 }); const del = useDeleteAssignment(); if (q.isLoading) return <LoadingState label="Loading assignments" />; if (q.isError) return <ErrorState title="Assignments unavailable" onRetry={() => q.refetch()} />; const data = q.data; return <div className="space-y-6"><div className="flex items-center justify-between"><div><p className="text-sm uppercase tracking-[0.2em] text-muted-foreground">Academic work</p><h1 className="text-3xl font-semibold">Assignments</h1></div>{admin && <Link className={buttonVariants()} href="/assignments/new">Create assignment</Link>}</div>{!data?.items.length ? <EmptyState title="No assignments" description="Assignments for your authorized classes will appear here." /> : <Card><CardHeader><CardTitle>Assignment records</CardTitle></CardHeader><CardContent><div className="space-y-3">{data.items.map((a) => <div key={a.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-4"><div><Link href={`/assignments/${a.id}`} className="font-medium hover:underline">{a.title}</Link><p className="text-sm text-muted-foreground">Subject #{a.subject_id} · Class #{a.academic_class_id} · Due {a.due_date}</p>{a.description && <p className="mt-1 text-sm text-muted-foreground">{a.description}</p>}</div>{admin && <button className="text-sm text-destructive" onClick={() => window.confirm('Delete this assignment?') && del.mutate(a.id)}>Delete</button>}</div>)}</div><div className="mt-4 flex justify-between text-sm"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {data.page} of {Math.max(1, data.total_pages)}</span><button disabled={page >= data.total_pages} onClick={() => setPage(page + 1)}>Next</button></div></CardContent></Card>}</div>; }
