"""add core management models

Revision ID: 042056e7b6c4
Revises: 4cb0843d7fb8
Create Date: 2026-08-27 14:24:32.039183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042056e7b6c4'
down_revision: Union[str, Sequence[str], None] = '4cb0843d7fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_classes_code'), 'academic_classes', ['code'], unique=True)
    op.create_table('academic_class_subjects',
    sa.Column('academic_class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_class_id'], ['academic_classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('academic_class_id', 'subject_id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_table('teacher_academic_classes',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('academic_class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_class_id'], ['academic_classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'academic_class_id')
    )
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('academic_class_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_students_academic_class_id'), 'students', ['academic_class_id'], unique=False)
    op.create_unique_constraint('uq_students_user_id', 'students', ['user_id'])
    op.create_foreign_key(
        'fk_students_user_id_users',
        'students',
        'users',
        ['user_id'],
        ['id'],
    )
    op.create_foreign_key(
        'fk_students_academic_class_id_academic_classes',
        'students',
        'academic_classes',
        ['academic_class_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_students_academic_class_id_academic_classes',
        'students',
        type_='foreignkey',
    )
    op.drop_constraint('fk_students_user_id_users', 'students', type_='foreignkey')
    op.drop_constraint('uq_students_user_id', 'students', type_='unique')
    op.drop_index(op.f('ix_students_academic_class_id'), table_name='students')
    op.drop_column('students', 'academic_class_id')
    op.drop_column('students', 'user_id')
    op.drop_table('teacher_subjects')
    op.drop_table('teacher_academic_classes')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_table('academic_class_subjects')
    op.drop_index(op.f('ix_academic_classes_code'), table_name='academic_classes')
    op.drop_table('academic_classes')
    # ### end Alembic commands ###
