'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useFees, useDeleteFee } from '@/lib/hooks/use-fees';
import { useAuth } from '@/lib/hooks/use-auth';
import { buttonVariants } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { LoadingState } from '@/components/states/LoadingState';
import { ErrorState } from '@/components/states/ErrorState';
import { EmptyState } from '@/components/states/EmptyState';
export default function FeesPage() { const [page, setPage] = useState(1); const { user } = useAuth(); const admin = user?.role === 'admin'; const q = useFees({ page, page_size: 20 }); const del = useDeleteFee(); if (q.isLoading) return <LoadingState label="Loading fees" />; if (q.isError) return <ErrorState title="Fees unavailable" onRetry={() => q.refetch()} />; const data = q.data; return <div className="space-y-6"><div className="flex items-center justify-between"><div><p className="text-sm uppercase tracking-[0.2em] text-muted-foreground">Finance</p><h1 className="text-3xl font-semibold">Fee records</h1></div>{admin && <Link className={buttonVariants()} href="/fees/new">Create fee</Link>}</div>{!data?.items.length ? <EmptyState title="No fee records" description="Fee records will appear here when they are created." /> : <Card><CardHeader><CardTitle>Payment records</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b"><tr><th className="px-3 py-3">Student</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Paid</th><th className="px-3 py-3">Due</th><th className="px-3 py-3">Due date</th><th className="px-3 py-3">Status</th><th /></tr></thead><tbody className="divide-y">{data.items.map((f) => <tr key={f.id}><td className="px-3 py-3">Student #{f.student_id}</td><td className="px-3 py-3">{f.amount.toFixed(2)}</td><td className="px-3 py-3">{f.paid_amount.toFixed(2)}</td><td className="px-3 py-3">{f.due_amount.toFixed(2)}</td><td className="px-3 py-3">{f.due_date}</td><td className="px-3 py-3 capitalize">{f.status}</td><td className="px-3 py-3"><Link href={`/fees/${f.id}`} className="underline">View</Link>{admin && <button className="ml-3 text-destructive" onClick={() => window.confirm('Delete this fee record?') && del.mutate(f.id)}>Delete</button>}</td></tr>)}</tbody></table></div><div className="mt-4 flex justify-between text-sm"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {data.page} of {Math.max(1, data.total_pages)}</span><button disabled={page >= data.total_pages} onClick={() => setPage(page + 1)}>Next</button></div></CardContent></Card>}</div>; }
